namespace Models
{
    public class TodoItem
    {
        public int Id { get; set; }
        public int BatchId { get; set; }
        public string? Title { get; set; }
        public bool AutoGenerated { get; set; } = false;
        public TodoStatus TodoStatus { get; set; }
        public DateTime DueDate { get; set; }
        public Priority Priority { get; set; }
        public Category Category { get; set; }
        public string? Notes { get; set; }
    }
}
