name: Build and Deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore "Farm backend/Entry Point.csproj"

    - name: Build and Publish Farm backend
      run: dotnet publish "Farm backend/Entry Point.csproj" --configuration Release --output ./publish

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.1.3
      with:
        publish-dir: ./publish
        production-deploy: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}